/**
 * ESTAS SON LOS CAMBIOS QUE FUERON AÑADIDOS EN ECMASCRIPT7
 */

/**
 * METEODO INCLUDES
 * NOS AYUDA A BUSCAR UN ELEMENTO DENTRO DE UN ARREGLO O STRING Y NOS PERMITE VALIDARLO DE ALGUNA MANERA
 * AQUI TENEMOS UN EJEMPLO DE VALIDACION
 */
let numbers = [1,2,3,7,8];

if(numbers.includes(2)){
    console.log('Si se encuentra el valor 7');
} else {
    console.log('No se encuentra');
}

/**
 * ELEVAR A LA POTENCIA
 * UTILIZAMOS UNA ESTRUCTURA BASE, EL VALOR DE EXPONENTE Y UN LUGAR PARA GUARDAR EL RESULTADO
 * ESTO NOS VA A SERVIR PARA ELEVEAR UN ELEMENTO "X" QUE ESTE CASO ES LA BASE
 * UNA POTENCIA "Y" QUE EN ESTE CASO EN MI EXPONENTE
 * PARA ESTO VAMOS A UNTLIZAR EL DOBLE ASTERISCO
 * PRESENTAMOS UN EJEMPLO DE COMO UTILIZARLO 
 * */

let base = 4;
let exponent = 5;
let result = base ** exponent;

console.log(result);

